-- users

CREATE TABLE IF NOT EXISTS users ();

ALTER TABLE users ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE users ADD COLUMN name VARCHAR(100) NOT NULL;
ALTER TABLE users ADD COLUMN email VARCHAR(100) NOT NULL UNIQUE;
ALTER TABLE users ADD COLUMN phone VARCHAR(100) NOT NULL UNIQUE;
ALTER TABLE users ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- messages

CREATE TABLE IF NOT EXISTS messages ();

ALTER TABLE messages ADD COLUMN id SERIAL PRIMARY KEY;
ALTER TABLE messages ADD COLUMN user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE messages ADD COLUMN content TEXT NOT NULL;
ALTER TABLE messages ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE messages ADD COLUMN deleted_at TIMESTAMP;
